package com.rilixtech.ionicons_typeface;

import android.content.Context;
import android.graphics.Typeface;

import com.rilixtech.materialfancybutton.typeface.IIcon;
import com.rilixtech.materialfancybutton.typeface.ITypeface;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;

public class Ionicons implements ITypeface {
	private static final String TTF_FILE = "ionicons-font-v2.0.1.1.ttf";
	private static final String MAPPING_FONT_PREFIX = "ioni";

	private static Typeface typeface = null;
	private static HashMap<String, Character> mChars;

	@Override public IIcon getIcon(String key) {
		return Icon.valueOf(key);
	}

	@Override public HashMap<String, Character> getCharacters() {
		if (mChars == null) {
			HashMap<String, Character> aChars = new HashMap<String, Character>();
			for (Icon v : Icon.values()) {
				aChars.put(v.name(), v.character);
			}
			mChars = aChars;
		}
		return mChars;
	}

	@Override public String getMappingPrefix() {
		return MAPPING_FONT_PREFIX;
	}

	@Override public String getFontName() {
		return "Ionicons";
	}

	@Override public String getVersion() {
		return "2.0.1.1";
	}

	@Override public int getIconCount() {
		return mChars.size();
	}

	@Override public Collection<String> getIcons() {
		Collection<String> icons = new LinkedList<String>();
		for (Icon value : Icon.values()) {
			icons.add(value.name());
		}
		return icons;
	}

	@Override public String getAuthor() {
		return "Benjsperry";
	}

	@Override public String getUrl() {
		return "http://ionicons.com/";
	}

	@Override public String getDescription() {
		return "The premium icon font for Ionic Framework.";
	}

	@Override public String getLicense() {
		return "MIT Licensed";
	}

	@Override public String getLicenseUrl() {
		return "https://github.com/driftyco/ionicons/blob/master/LICENSE";
	}

	@Override public Typeface getTypeface(Context context) {
		if (typeface == null) {
			try {
				typeface = Typeface.createFromAsset(context.getAssets(), "fonts/" + TTF_FILE);
			} catch (Exception e) {
				return null;
			}
		}
		return typeface;
	}

    public enum Icon implements IIcon {
        ioni_alert('\uf101'),
		ioni_alert_circled('\uf100'),
		ioni_android_add('\uf2c7'),
		ioni_android_add_circle('\uf359'),
		ioni_android_alarm_clock('\uf35a'),
		ioni_android_alert('\uf35b'),
		ioni_android_apps('\uf35c'),
		ioni_android_archive('\uf2c9'),
		ioni_android_arrow_back('\uf2ca'),
		ioni_android_arrow_down('\uf35d'),
		ioni_android_arrow_dropdown('\uf35f'),
		ioni_android_arrow_dropdown_circle('\uf35e'),
		ioni_android_arrow_dropleft('\uf361'),
		ioni_android_arrow_dropleft_circle('\uf360'),
		ioni_android_arrow_dropright('\uf363'),
		ioni_android_arrow_dropright_circle('\uf362'),
		ioni_android_arrow_dropup('\uf365'),
		ioni_android_arrow_dropup_circle('\uf364'),
		ioni_android_arrow_forward('\uf30f'),
		ioni_android_arrow_up('\uf366'),
		ioni_android_attach('\uf367'),
		ioni_android_bar('\uf368'),
		ioni_android_bicycle('\uf369'),
		ioni_android_boat('\uf36a'),
		ioni_android_bookmark('\uf36b'),
		ioni_android_bulb('\uf36c'),
		ioni_android_bus('\uf36d'),
		ioni_android_calendar('\uf2d1'),
		ioni_android_call('\uf2d2'),
		ioni_android_camera('\uf2d3'),
		ioni_android_cancel('\uf36e'),
		ioni_android_car('\uf36f'),
		ioni_android_cart('\uf370'),
		ioni_android_chat('\uf2d4'),
		ioni_android_checkbox('\uf374'),
		ioni_android_checkbox_blank('\uf371'),
		ioni_android_checkbox_outline('\uf373'),
		ioni_android_checkbox_outline_blank('\uf372'),
		ioni_android_checkmark_circle('\uf375'),
		ioni_android_clipboard('\uf376'),
		ioni_android_close('\uf2d7'),
		ioni_android_cloud('\uf37a'),
		ioni_android_cloud_circle('\uf377'),
		ioni_android_cloud_done('\uf378'),
		ioni_android_cloud_outline('\uf379'),
		ioni_android_color_palette('\uf37b'),
		ioni_android_compass('\uf37c'),
		ioni_android_contact('\uf2d8'),
		ioni_android_contacts('\uf2d9'),
		ioni_android_contract('\uf37d'),
		ioni_android_create('\uf37e'),
		ioni_android_delete('\uf37f'),
		ioni_android_desktop('\uf380'),
		ioni_android_document('\uf381'),
		ioni_android_done('\uf383'),
		ioni_android_done_all('\uf382'),
		ioni_android_download('\uf2dd'),
		ioni_android_drafts('\uf384'),
		ioni_android_exit('\uf385'),
		ioni_android_expand('\uf386'),
		ioni_android_favorite('\uf388'),
		ioni_android_favorite_outline('\uf387'),
		ioni_android_film('\uf389'),
		ioni_android_folder('\uf2e0'),
		ioni_android_folder_open('\uf38a'),
		ioni_android_funnel('\uf38b'),
		ioni_android_globe('\uf38c'),
		ioni_android_hand('\uf2e3'),
		ioni_android_hangout('\uf38d'),
		ioni_android_happy('\uf38e'),
		ioni_android_home('\uf38f'),
		ioni_android_image('\uf2e4'),
		ioni_android_laptop('\uf390'),
		ioni_android_list('\uf391'),
		ioni_android_locate('\uf2e9'),
		ioni_android_lock('\uf392'),
		ioni_android_mail('\uf2eb'),
		ioni_android_map('\uf393'),
		ioni_android_menu('\uf394'),
		ioni_android_microphone('\uf2ec'),
		ioni_android_microphone_off('\uf395'),
		ioni_android_more_horizontal('\uf396'),
		ioni_android_more_vertical('\uf397'),
		ioni_android_navigate('\uf398'),
		ioni_android_notifications('\uf39b'),
		ioni_android_notifications_none('\uf399'),
		ioni_android_notifications_off('\uf39a'),
		ioni_android_open('\uf39c'),
		ioni_android_options('\uf39d'),
		ioni_android_people('\uf39e'),
		ioni_android_person('\uf3a0'),
		ioni_android_person_add('\uf39f'),
		ioni_android_phone_landscape('\uf3a1'),
		ioni_android_phone_portrait('\uf3a2'),
		ioni_android_pin('\uf3a3'),
		ioni_android_plane('\uf3a4'),
		ioni_android_playstore('\uf2f0'),
		ioni_android_print('\uf3a5'),
		ioni_android_radio_button_off('\uf3a6'),
		ioni_android_radio_button_on('\uf3a7'),
		ioni_android_refresh('\uf3a8'),
		ioni_android_remove('\uf2f4'),
		ioni_android_remove_circle('\uf3a9'),
		ioni_android_restaurant('\uf3aa'),
		ioni_android_sad('\uf3ab'),
		ioni_android_search('\uf2f5'),
		ioni_android_send('\uf2f6'),
		ioni_android_settings('\uf2f7'),
		ioni_android_share('\uf2f8'),
		ioni_android_share_alt('\uf3ac'),
		ioni_android_star('\uf2fc'),
		ioni_android_star_half('\uf3ad'),
		ioni_android_star_outline('\uf3ae'),
		ioni_android_stopwatch('\uf2fd'),
		ioni_android_subway('\uf3af'),
		ioni_android_sunny('\uf3b0'),
		ioni_android_sync('\uf3b1'),
		ioni_android_textsms('\uf3b2'),
		ioni_android_time('\uf3b3'),
		ioni_android_train('\uf3b4'),
		ioni_android_unlock('\uf3b5'),
		ioni_android_upload('\uf3b6'),
		ioni_android_volume_down('\uf3b7'),
		ioni_android_volume_mute('\uf3b8'),
		ioni_android_volume_off('\uf3b9'),
		ioni_android_volume_up('\uf3ba'),
		ioni_android_walk('\uf3bb'),
		ioni_android_warning('\uf3bc'),
		ioni_android_watch('\uf3bd'),
		ioni_android_wifi('\uf305'),
		ioni_aperture('\uf313'),
		ioni_archive('\uf102'),
		ioni_arrow_down_a('\uf103'),
		ioni_arrow_down_b('\uf104'),
		ioni_arrow_down_c('\uf105'),
		ioni_arrow_expand('\uf25e'),
		ioni_arrow_graph_down_left('\uf25f'),
		ioni_arrow_graph_down_right('\uf260'),
		ioni_arrow_graph_up_left('\uf261'),
		ioni_arrow_graph_up_right('\uf262'),
		ioni_arrow_left_a('\uf106'),
		ioni_arrow_left_b('\uf107'),
		ioni_arrow_left_c('\uf108'),
		ioni_arrow_move('\uf263'),
		ioni_arrow_resize('\uf264'),
		ioni_arrow_return_left('\uf265'),
		ioni_arrow_return_right('\uf266'),
		ioni_arrow_right_a('\uf109'),
		ioni_arrow_right_b('\uf10a'),
		ioni_arrow_right_c('\uf10b'),
		ioni_arrow_shrink('\uf267'),
		ioni_arrow_swap('\uf268'),
		ioni_arrow_up_a('\uf10c'),
		ioni_arrow_up_b('\uf10d'),
		ioni_arrow_up_c('\uf10e'),
		ioni_asterisk('\uf314'),
		ioni_at('\uf10f'),
		ioni_backspace('\uf3bf'),
		ioni_backspace_outline('\uf3be'),
		ioni_bag('\uf110'),
		ioni_battery_charging('\uf111'),
		ioni_battery_empty('\uf112'),
		ioni_battery_full('\uf113'),
		ioni_battery_half('\uf114'),
		ioni_battery_low('\uf115'),
		ioni_beaker('\uf269'),
		ioni_beer('\uf26a'),
		ioni_bluetooth('\uf116'),
		ioni_bonfire('\uf315'),
		ioni_bookmark('\uf26b'),
		ioni_bowtie('\uf3c0'),
		ioni_briefcase('\uf26c'),
		ioni_bug('\uf2be'),
		ioni_calculator('\uf26d'),
		ioni_calendar('\uf117'),
		ioni_camera('\uf118'),
		ioni_card('\uf119'),
		ioni_cash('\uf316'),
		ioni_chatbox('\uf11b'),
		ioni_chatbox_working('\uf11a'),
		ioni_chatboxes('\uf11c'),
		ioni_chatbubble('\uf11e'),
		ioni_chatbubble_working('\uf11d'),
		ioni_chatbubbles('\uf11f'),
		ioni_checkmark('\uf122'),
		ioni_checkmark_circled('\uf120'),
		ioni_checkmark_round('\uf121'),
		ioni_chevron_down('\uf123'),
		ioni_chevron_left('\uf124'),
		ioni_chevron_right('\uf125'),
		ioni_chevron_up('\uf126'),
		ioni_clipboard('\uf127'),
		ioni_clock('\uf26e'),
		ioni_close('\uf12a'),
		ioni_close_circled('\uf128'),
		ioni_close_round('\uf129'),
		ioni_closed_captioning('\uf317'),
		ioni_cloud('\uf12b'),
		ioni_code('\uf271'),
		ioni_code_download('\uf26f'),
		ioni_code_working('\uf270'),
		ioni_coffee('\uf272'),
		ioni_compass('\uf273'),
		ioni_compose('\uf12c'),
		ioni_connectioni_bars('\uf274'),
		ioni_contrast('\uf275'),
		ioni_crop('\uf3c1'),
		ioni_cube('\uf318'),
		ioni_disc('\uf12d'),
		ioni_document('\uf12f'),
		ioni_documenti_text('\uf12e'),
		ioni_drag('\uf130'),
		ioni_earth('\uf276'),
		ioni_easel('\uf3c2'),
		ioni_edit('\uf2bf'),
		ioni_egg('\uf277'),
		ioni_eject('\uf131'),
		ioni_email('\uf132'),
		ioni_email_unread('\uf3c3'),
		ioni_erlenmeyer_flask('\uf3c5'),
		ioni_erlenmeyer_flask_bubbles('\uf3c4'),
		ioni_eye('\uf133'),
		ioni_eye_disabled('\uf306'),
		ioni_female('\uf278'),
		ioni_filing('\uf134'),
		ioni_film_marker('\uf135'),
		ioni_fireball('\uf319'),
		ioni_flag('\uf279'),
		ioni_flame('\uf31a'),
		ioni_flash('\uf137'),
		ioni_flash_off('\uf136'),
		ioni_folder('\uf139'),
		ioni_fork('\uf27a'),
		ioni_fork_repo('\uf2c0'),
		ioni_forward('\uf13a'),
		ioni_funnel('\uf31b'),
		ioni_gear_a('\uf13d'),
		ioni_gear_b('\uf13e'),
		ioni_grid('\uf13f'),
		ioni_hammer('\uf27b'),
		ioni_happy('\uf31c'),
		ioni_happy_outline('\uf3c6'),
		ioni_headphone('\uf140'),
		ioni_heart('\uf141'),
		ioni_heart_broken('\uf31d'),
		ioni_help('\uf143'),
		ioni_help_buoy('\uf27c'),
		ioni_help_circled('\uf142'),
		ioni_home('\uf144'),
		ioni_icecream('\uf27d'),
		ioni_image('\uf147'),
		ioni_images('\uf148'),
		ioni_information('\uf14a'),
		ioni_informationi_circled('\uf149'),
		ioni_ionic('\uf14b'),
		ioni_ios_alarm('\uf3c8'),
		ioni_ios_alarm_outline('\uf3c7'),
		ioni_ios_albums('\uf3ca'),
		ioni_ios_albums_outline('\uf3c9'),
		ioni_ios_americanfootball('\uf3cc'),
		ioni_ios_americanfootball_outline('\uf3cb'),
		ioni_ios_analytics('\uf3ce'),
		ioni_ios_analytics_outline('\uf3cd'),
		ioni_ios_arrow_back('\uf3cf'),
		ioni_ios_arrow_down('\uf3d0'),
		ioni_ios_arrow_forward('\uf3d1'),
		ioni_ios_arrow_left('\uf3d2'),
		ioni_ios_arrow_right('\uf3d3'),
		ioni_ios_arrow_thin_down('\uf3d4'),
		ioni_ios_arrow_thin_left('\uf3d5'),
		ioni_ios_arrow_thin_right('\uf3d6'),
		ioni_ios_arrow_thin_up('\uf3d7'),
		ioni_ios_arrow_up('\uf3d8'),
		ioni_ios_at('\uf3da'),
		ioni_ios_at_outline('\uf3d9'),
		ioni_ios_barcode('\uf3dc'),
		ioni_ios_barcode_outline('\uf3db'),
		ioni_ios_baseball('\uf3de'),
		ioni_ios_baseball_outline('\uf3dd'),
		ioni_ios_basketball('\uf3e0'),
		ioni_ios_basketball_outline('\uf3df'),
		ioni_ios_bell('\uf3e2'),
		ioni_ios_bell_outline('\uf3e1'),
		ioni_ios_body('\uf3e4'),
		ioni_ios_body_outline('\uf3e3'),
		ioni_ios_bolt('\uf3e6'),
		ioni_ios_bolt_outline('\uf3e5'),
		ioni_ios_book('\uf3e8'),
		ioni_ios_book_outline('\uf3e7'),
		ioni_ios_bookmarks('\uf3ea'),
		ioni_ios_bookmarks_outline('\uf3e9'),
		ioni_ios_box('\uf3ec'),
		ioni_ios_box_outline('\uf3eb'),
		ioni_ios_briefcase('\uf3ee'),
		ioni_ios_briefcase_outline('\uf3ed'),
		ioni_ios_browsers('\uf3f0'),
		ioni_ios_browsers_outline('\uf3ef'),
		ioni_ios_calculator('\uf3f2'),
		ioni_ios_calculator_outline('\uf3f1'),
		ioni_ios_calendar('\uf3f4'),
		ioni_ios_calendar_outline('\uf3f3'),
		ioni_ios_camera('\uf3f6'),
		ioni_ios_camera_outline('\uf3f5'),
		ioni_ios_cart('\uf3f8'),
		ioni_ios_cart_outline('\uf3f7'),
		ioni_ios_chatboxes('\uf3fa'),
		ioni_ios_chatboxes_outline('\uf3f9'),
		ioni_ios_chatbubble('\uf3fc'),
		ioni_ios_chatbubble_outline('\uf3fb'),
		ioni_ios_checkmark('\uf3ff'),
		ioni_ios_checkmark_empty('\uf3fd'),
		ioni_ios_checkmark_outline('\uf3fe'),
		ioni_ios_circle_filled('\uf400'),
		ioni_ios_circle_outline('\uf401'),
		ioni_ios_clock('\uf403'),
		ioni_ios_clock_outline('\uf402'),
		ioni_ios_close('\uf406'),
		ioni_ios_close_empty('\uf404'),
		ioni_ios_close_outline('\uf405'),
		ioni_ios_cloud('\uf40c'),
		ioni_ios_cloud_download('\uf408'),
		ioni_ios_cloud_download_outline('\uf407'),
		ioni_ios_cloud_outline('\uf409'),
		ioni_ios_cloud_upload('\uf40b'),
		ioni_ios_cloud_upload_outline('\uf40a'),
		ioni_ios_cloudy('\uf410'),
		ioni_ios_cloudy_night('\uf40e'),
		ioni_ios_cloudy_night_outline('\uf40d'),
		ioni_ios_cloudy_outline('\uf40f'),
		ioni_ios_cog('\uf412'),
		ioni_ios_cog_outline('\uf411'),
		ioni_ios_color_filter('\uf414'),
		ioni_ios_color_filter_outline('\uf413'),
		ioni_ios_color_wand('\uf416'),
		ioni_ios_color_wand_outline('\uf415'),
		ioni_ios_compose('\uf418'),
		ioni_ios_compose_outline('\uf417'),
		ioni_ios_contact('\uf41a'),
		ioni_ios_contact_outline('\uf419'),
		ioni_ios_copy('\uf41c'),
		ioni_ios_copy_outline('\uf41b'),
		ioni_ios_crop('\uf41e'),
		ioni_ios_crop_strong('\uf41d'),
		ioni_ios_download('\uf420'),
		ioni_ios_download_outline('\uf41f'),
		ioni_ios_drag('\uf421'),
		ioni_ios_email('\uf423'),
		ioni_ios_email_outline('\uf422'),
		ioni_ios_eye('\uf425'),
		ioni_ios_eye_outline('\uf424'),
		ioni_ios_fastforward('\uf427'),
		ioni_ios_fastforward_outline('\uf426'),
		ioni_ios_filing('\uf429'),
		ioni_ios_filing_outline('\uf428'),
		ioni_ios_film('\uf42b'),
		ioni_ios_film_outline('\uf42a'),
		ioni_ios_flag('\uf42d'),
		ioni_ios_flag_outline('\uf42c'),
		ioni_ios_flame('\uf42f'),
		ioni_ios_flame_outline('\uf42e'),
		ioni_ios_flask('\uf431'),
		ioni_ios_flask_outline('\uf430'),
		ioni_ios_flower('\uf433'),
		ioni_ios_flower_outline('\uf432'),
		ioni_ios_folder('\uf435'),
		ioni_ios_folder_outline('\uf434'),
		ioni_ios_football('\uf437'),
		ioni_ios_football_outline('\uf436'),
		ioni_ios_game_controller_a('\uf439'),
		ioni_ios_game_controller_a_outline('\uf438'),
		ioni_ios_game_controller_b('\uf43b'),
		ioni_ios_game_controller_b_outline('\uf43a'),
		ioni_ios_gear('\uf43d'),
		ioni_ios_gear_outline('\uf43c'),
		ioni_ios_glasses('\uf43f'),
		ioni_ios_glasses_outline('\uf43e'),
		ioni_ios_grid_view('\uf441'),
		ioni_ios_grid_view_outline('\uf440'),
		ioni_ios_heart('\uf443'),
		ioni_ios_heart_outline('\uf442'),
		ioni_ios_help('\uf446'),
		ioni_ios_help_empty('\uf444'),
		ioni_ios_help_outline('\uf445'),
		ioni_ios_home('\uf448'),
		ioni_ios_home_outline('\uf447'),
		ioni_ios_infinite('\uf44a'),
		ioni_ios_infinite_outline('\uf449'),
		ioni_ios_information('\uf44d'),
		ioni_ios_informationi_empty('\uf44b'),
		ioni_ios_informationi_outline('\uf44c'),
		ioni_ios_ionic_outline('\uf44e'),
		ioni_ios_keypad('\uf450'),
		ioni_ios_keypad_outline('\uf44f'),
		ioni_ios_lightbulb('\uf452'),
		ioni_ios_lightbulb_outline('\uf451'),
		ioni_ios_list('\uf454'),
		ioni_ios_list_outline('\uf453'),
		ioni_ios_location('\uf456'),
		ioni_ios_locationi_outline('\uf455'),
		ioni_ios_locked('\uf458'),
		ioni_ios_locked_outline('\uf457'),
		ioni_ios_loop('\uf45a'),
		ioni_ios_loop_strong('\uf459'),
		ioni_ios_medical('\uf45c'),
		ioni_ios_medical_outline('\uf45b'),
		ioni_ios_medkit('\uf45e'),
		ioni_ios_medkit_outline('\uf45d'),
		ioni_ios_mic('\uf461'),
		ioni_ios_mic_off('\uf45f'),
		ioni_ios_mic_outline('\uf460'),
		ioni_ios_minus('\uf464'),
		ioni_ios_minus_empty('\uf462'),
		ioni_ios_minus_outline('\uf463'),
		ioni_ios_monitor('\uf466'),
		ioni_ios_monitor_outline('\uf465'),
		ioni_ios_moon('\uf468'),
		ioni_ios_moon_outline('\uf467'),
		ioni_ios_more('\uf46a'),
		ioni_ios_more_outline('\uf469'),
		ioni_ios_musical_note('\uf46b'),
		ioni_ios_musical_notes('\uf46c'),
		ioni_ios_navigate('\uf46e'),
		ioni_ios_navigate_outline('\uf46d'),
		ioni_ios_nutrition('\uf470'),
		ioni_ios_nutritioni_outline('\uf46f'),
		ioni_ios_paper('\uf472'),
		ioni_ios_paper_outline('\uf471'),
		ioni_ios_paperplane('\uf474'),
		ioni_ios_paperplane_outline('\uf473'),
		ioni_ios_partlysunny('\uf476'),
		ioni_ios_partlysunny_outline('\uf475'),
		ioni_ios_pause('\uf478'),
		ioni_ios_pause_outline('\uf477'),
		ioni_ios_paw('\uf47a'),
		ioni_ios_paw_outline('\uf479'),
		ioni_ios_people('\uf47c'),
		ioni_ios_people_outline('\uf47b'),
		ioni_ios_person('\uf47e'),
		ioni_ios_person_outline('\uf47d'),
		ioni_ios_personadd('\uf480'),
		ioni_ios_personadd_outline('\uf47f'),
		ioni_ios_photos('\uf482'),
		ioni_ios_photos_outline('\uf481'),
		ioni_ios_pie('\uf484'),
		ioni_ios_pie_outline('\uf483'),
		ioni_ios_pint('\uf486'),
		ioni_ios_pint_outline('\uf485'),
		ioni_ios_play('\uf488'),
		ioni_ios_play_outline('\uf487'),
		ioni_ios_plus('\uf48b'),
		ioni_ios_plus_empty('\uf489'),
		ioni_ios_plus_outline('\uf48a'),
		ioni_ios_pricetag('\uf48d'),
		ioni_ios_pricetag_outline('\uf48c'),
		ioni_ios_pricetags('\uf48f'),
		ioni_ios_pricetags_outline('\uf48e'),
		ioni_ios_printer('\uf491'),
		ioni_ios_printer_outline('\uf490'),
		ioni_ios_pulse('\uf493'),
		ioni_ios_pulse_strong('\uf492'),
		ioni_ios_rainy('\uf495'),
		ioni_ios_rainy_outline('\uf494'),
		ioni_ios_recording('\uf497'),
		ioni_ios_recording_outline('\uf496'),
		ioni_ios_redo('\uf499'),
		ioni_ios_redo_outline('\uf498'),
		ioni_ios_refresh('\uf49c'),
		ioni_ios_refresh_empty('\uf49a'),
		ioni_ios_refresh_outline('\uf49b'),
		ioni_ios_reload('\uf49d'),
		ioni_ios_reverse_camera('\uf49f'),
		ioni_ios_reverse_camera_outline('\uf49e'),
		ioni_ios_rewind('\uf4a1'),
		ioni_ios_rewind_outline('\uf4a0'),
		ioni_ios_rose('\uf4a3'),
		ioni_ios_rose_outline('\uf4a2'),
		ioni_ios_search('\uf4a5'),
		ioni_ios_search_strong('\uf4a4'),
		ioni_ios_settings('\uf4a7'),
		ioni_ios_settings_strong('\uf4a6'),
		ioni_ios_shuffle('\uf4a9'),
		ioni_ios_shuffle_strong('\uf4a8'),
		ioni_ios_skipbackward('\uf4ab'),
		ioni_ios_skipbackward_outline('\uf4aa'),
		ioni_ios_skipforward('\uf4ad'),
		ioni_ios_skipforward_outline('\uf4ac'),
		ioni_ios_snowy('\uf4ae'),
		ioni_ios_speedometer('\uf4b0'),
		ioni_ios_speedometer_outline('\uf4af'),
		ioni_ios_star('\uf4b3'),
		ioni_ios_star_half('\uf4b1'),
		ioni_ios_star_outline('\uf4b2'),
		ioni_ios_stopwatch('\uf4b5'),
		ioni_ios_stopwatch_outline('\uf4b4'),
		ioni_ios_sunny('\uf4b7'),
		ioni_ios_sunny_outline('\uf4b6'),
		ioni_ios_telephone('\uf4b9'),
		ioni_ios_telephone_outline('\uf4b8'),
		ioni_ios_tennisball('\uf4bb'),
		ioni_ios_tennisball_outline('\uf4ba'),
		ioni_ios_thunderstorm('\uf4bd'),
		ioni_ios_thunderstorm_outline('\uf4bc'),
		ioni_ios_time('\uf4bf'),
		ioni_ios_time_outline('\uf4be'),
		ioni_ios_timer('\uf4c1'),
		ioni_ios_timer_outline('\uf4c0'),
		ioni_ios_toggle('\uf4c3'),
		ioni_ios_toggle_outline('\uf4c2'),
		ioni_ios_trash('\uf4c5'),
		ioni_ios_trash_outline('\uf4c4'),
		ioni_ios_undo('\uf4c7'),
		ioni_ios_undo_outline('\uf4c6'),
		ioni_ios_unlocked('\uf4c9'),
		ioni_ios_unlocked_outline('\uf4c8'),
		ioni_ios_upload('\uf4cb'),
		ioni_ios_upload_outline('\uf4ca'),
		ioni_ios_videocam('\uf4cd'),
		ioni_ios_videocam_outline('\uf4cc'),
		ioni_ios_volume_high('\uf4ce'),
		ioni_ios_volume_low('\uf4cf'),
		ioni_ios_wineglass('\uf4d1'),
		ioni_ios_wineglass_outline('\uf4d0'),
		ioni_ios_world('\uf4d3'),
		ioni_ios_world_outline('\uf4d2'),
		ioni_ipad('\uf1f9'),
		ioni_iphone('\uf1fa'),
		ioni_ipod('\uf1fb'),
		ioni_jet('\uf295'),
		ioni_key('\uf296'),
		ioni_knife('\uf297'),
		ioni_laptop('\uf1fc'),
		ioni_leaf('\uf1fd'),
		ioni_levels('\uf298'),
		ioni_lightbulb('\uf299'),
		ioni_link('\uf1fe'),
		ioni_load_a('\uf29a'),
		ioni_load_b('\uf29b'),
		ioni_load_c('\uf29c'),
		ioni_load_d('\uf29d'),
		ioni_location('\uf1ff'),
		ioni_lock_combination('\uf4d4'),
		ioni_locked('\uf200'),
		ioni_log_in('\uf29e'),
		ioni_log_out('\uf29f'),
		ioni_loop('\uf201'),
		ioni_magnet('\uf2a0'),
		ioni_male('\uf2a1'),
		ioni_man('\uf202'),
		ioni_map('\uf203'),
		ioni_medkit('\uf2a2'),
		ioni_merge('\uf33f'),
		ioni_mic_a('\uf204'),
		ioni_mic_b('\uf205'),
		ioni_mic_c('\uf206'),
		ioni_minus('\uf209'),
		ioni_minus_circled('\uf207'),
		ioni_minus_round('\uf208'),
		ioni_model_s('\uf2c1'),
		ioni_monitor('\uf20a'),
		ioni_more('\uf20b'),
		ioni_mouse('\uf340'),
		ioni_music_note('\uf20c'),
		ioni_navicon('\uf20e'),
		ioni_navicon_round('\uf20d'),
		ioni_navigate('\uf2a3'),
		ioni_network('\uf341'),
		ioni_no_smoking('\uf2c2'),
		ioni_nuclear('\uf2a4'),
		ioni_outlet('\uf342'),
		ioni_paintbrush('\uf4d5'),
		ioni_paintbucket('\uf4d6'),
		ioni_paper_airplane('\uf2c3'),
		ioni_paperclip('\uf20f'),
		ioni_pause('\uf210'),
		ioni_person('\uf213'),
		ioni_person_add('\uf211'),
		ioni_person_stalker('\uf212'),
		ioni_pie_graph('\uf2a5'),
		ioni_pin('\uf2a6'),
		ioni_pinpoint('\uf2a7'),
		ioni_pizza('\uf2a8'),
		ioni_plane('\uf214'),
		ioni_planet('\uf343'),
		ioni_play('\uf215'),
		ioni_playstation('\uf30a'),
		ioni_plus('\uf218'),
		ioni_plus_circled('\uf216'),
		ioni_plus_round('\uf217'),
		ioni_podium('\uf344'),
		ioni_pound('\uf219'),
		ioni_power('\uf2a9'),
		ioni_pricetag('\uf2aa'),
		ioni_pricetags('\uf2ab'),
		ioni_printer('\uf21a'),
		ioni_pull_request('\uf345'),
		ioni_qr_scanner('\uf346'),
		ioni_quote('\uf347'),
		ioni_radio_waves('\uf2ac'),
		ioni_record('\uf21b'),
		ioni_refresh('\uf21c'),
		ioni_reply('\uf21e'),
		ioni_reply_all('\uf21d'),
		ioni_ribbon_a('\uf348'),
		ioni_ribbon_b('\uf349'),
		ioni_sad('\uf34a'),
		ioni_sad_outline('\uf4d7'),
		ioni_scissors('\uf34b'),
		ioni_search('\uf21f'),
		ioni_settings('\uf2ad'),
		ioni_share('\uf220'),
		ioni_shuffle('\uf221'),
		ioni_skip_backward('\uf222'),
		ioni_skip_forward('\uf223'),
		ioni_social_android('\uf225'),
		ioni_social_android_outline('\uf224'),
		ioni_social_angular('\uf4d9'),
		ioni_social_angular_outline('\uf4d8'),
		ioni_social_apple('\uf227'),
		ioni_social_apple_outline('\uf226'),
		ioni_social_bitcoin('\uf2af'),
		ioni_social_bitcoin_outline('\uf2ae'),
		ioni_social_buffer('\uf229'),
		ioni_social_buffer_outline('\uf228'),
		ioni_social_chrome('\uf4db'),
		ioni_social_chrome_outline('\uf4da'),
		ioni_social_codepen('\uf4dd'),
		ioni_social_codepen_outline('\uf4dc'),
		ioni_social_css3('\uf4df'),
		ioni_social_css3_outline('\uf4de'),
		ioni_social_designernews('\uf22b'),
		ioni_social_designernews_outline('\uf22a'),
		ioni_social_dribbble('\uf22d'),
		ioni_social_dribbble_outline('\uf22c'),
		ioni_social_dropbox('\uf22f'),
		ioni_social_dropbox_outline('\uf22e'),
		ioni_social_euro('\uf4e1'),
		ioni_social_euro_outline('\uf4e0'),
		ioni_social_facebook('\uf231'),
		ioni_social_facebook_outline('\uf230'),
		ioni_social_foursquare('\uf34d'),
		ioni_social_foursquare_outline('\uf34c'),
		ioni_social_freebsd_devil('\uf2c4'),
		ioni_social_github('\uf233'),
		ioni_social_github_outline('\uf232'),
		ioni_social_google('\uf34f'),
		ioni_social_google_outline('\uf34e'),
		ioni_social_googleplus('\uf235'),
		ioni_social_googleplus_outline('\uf234'),
		ioni_social_hackernews('\uf237'),
		ioni_social_hackernews_outline('\uf236'),
		ioni_social_html5('\uf4e3'),
		ioni_social_html5_outline('\uf4e2'),
		ioni_social_instagram('\uf351'),
		ioni_social_instagram_outline('\uf350'),
		ioni_social_javascript('\uf4e5'),
		ioni_social_javascript_outline('\uf4e4'),
		ioni_social_linkedin('\uf239'),
		ioni_social_linkedin_outline('\uf238'),
		ioni_social_markdown('\uf4e6'),
		ioni_social_nodejs('\uf4e7'),
		ioni_social_octocat('\uf4e8'),
		ioni_social_pinterest('\uf2b1'),
		ioni_social_pinterest_outline('\uf2b0'),
		ioni_social_python('\uf4e9'),
		ioni_social_reddit('\uf23b'),
		ioni_social_reddit_outline('\uf23a'),
		ioni_social_rss('\uf23d'),
		ioni_social_rss_outline('\uf23c'),
		ioni_social_sass('\uf4ea'),
		ioni_social_skype('\uf23f'),
		ioni_social_skype_outline('\uf23e'),
		ioni_social_snapchat('\uf4ec'),
		ioni_social_snapchat_outline('\uf4eb'),
		ioni_social_tumblr('\uf241'),
		ioni_social_tumblr_outline('\uf240'),
		ioni_social_tux('\uf2c5'),
		ioni_social_twitch('\uf4ee'),
		ioni_social_twitch_outline('\uf4ed'),
		ioni_social_twitter('\uf243'),
		ioni_social_twitter_outline('\uf242'),
		ioni_social_usd('\uf353'),
		ioni_social_usd_outline('\uf352'),
		ioni_social_vimeo('\uf245'),
		ioni_social_vimeo_outline('\uf244'),
		ioni_social_whatsapp('\uf4f0'),
		ioni_social_whatsapp_outline('\uf4ef'),
		ioni_social_windows('\uf247'),
		ioni_social_windows_outline('\uf246'),
		ioni_social_wordpress('\uf249'),
		ioni_social_wordpress_outline('\uf248'),
		ioni_social_yahoo('\uf24b'),
		ioni_social_yahoo_outline('\uf24a'),
		ioni_social_yen('\uf4f2'),
		ioni_social_yen_outline('\uf4f1'),
		ioni_social_youtube('\uf24d'),
		ioni_social_youtube_outline('\uf24c'),
		ioni_soup_can('\uf4f4'),
		ioni_soup_can_outline('\uf4f3'),
		ioni_speakerphone('\uf2b2'),
		ioni_speedometer('\uf2b3'),
		ioni_spoon('\uf2b4'),
		ioni_star('\uf24e'),
		ioni_stats_bars('\uf2b5'),
		ioni_steam('\uf30b'),
		ioni_stop('\uf24f'),
		ioni_thermometer('\uf2b6'),
		ioni_thumbsdown('\uf250'),
		ioni_thumbsup('\uf251'),
		ioni_toggle('\uf355'),
		ioni_toggle_filled('\uf354'),
		ioni_transgender('\uf4f5'),
		ioni_trash_a('\uf252'),
		ioni_trash_b('\uf253'),
		ioni_trophy('\uf356'),
		ioni_tshirt('\uf4f7'),
		ioni_tshirt_outline('\uf4f6'),
		ioni_umbrella('\uf2b7'),
		ioni_university('\uf357'),
		ioni_unlocked('\uf254'),
		ioni_upload('\uf255'),
		ioni_usb('\uf2b8'),
		ioni_videocamera('\uf256'),
		ioni_volume_high('\uf257'),
		ioni_volume_low('\uf258'),
		ioni_volume_medium('\uf259'),
		ioni_volume_mute('\uf25a'),
		ioni_wand('\uf358'),
		ioni_waterdrop('\uf25b'),
		ioni_wifi('\uf25c'),
		ioni_wineglass('\uf2b9'),
		ioni_woman('\uf25d'),
		ioni_wrench('\uf2ba'),
		ioni_xbox('\uf30c');

        char character;

        Icon(char character) {
            this.character = character;
        }

        public String getFormattedName() {
            return "{" + name() + "}";
        }

        public char getCharacter() {
            return character;
        }

        public String getName() {
            return name();
        }

        // remember the typeface so we can use it later
        private static ITypeface typeface;

        public ITypeface getTypeface() {
            if (typeface == null) {
                typeface = new Ionicons();
            }
            return typeface;
        }
    }
}
